# stages:
#   - verify
#   - deploy

# default:
#   image: node:20-bookworm-slim
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules/

# workflow:
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# before_script:
#   - npm ci

# typecheck:
#   stage: verify
#   script:
#     - npm run typecheck

# deploy:
#   stage: deploy
#   script:
#     - npm run deploy
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
#   environment:
#     name: production
